const T={
open:{
'zh-CN':{title:'如何通过专属链接开户',intro:'使用网站内的专属开户链接完成注册，便于后续核对账户归属和满返申请。',steps:['点击网站上的“通过专属链接开户”。','在TMGM相关注册页面填写资料并完成身份认证。','账户审核完成后，保存TMGM注册邮箱和交易账号。','返回本网站提交满返申请。'],note:'请勿向任何人提供交易密码、验证码、银行卡资料或证件图片。'},
'zh-TW':{title:'如何透過專屬連結開戶',intro:'使用網站內的專屬開戶連結完成註冊，方便後續核對帳戶歸屬及滿返申請。',steps:['點擊網站上的「透過專屬連結開戶」。','在TMGM相關註冊頁面填寫資料並完成身份認證。','帳戶審核完成後，保存TMGM註冊電郵和交易帳號。','返回本網站提交滿返申請。'],note:'請勿向任何人提供交易密碼、驗證碼、銀行卡資料或證件圖片。'},
en:{title:'Open through the referral link',intro:'Use the referral link on this website so the account can be reviewed for attribution and rebate eligibility.',steps:['Select “Open account” on the website.','Complete registration and identity verification on the relevant TMGM page.','After approval, keep your registered email and trading account number.','Return to this website and submit the rebate application.'],note:'Never provide trading passwords, verification codes, card details or identity-document images.'},
ms:{title:'Buka akaun melalui pautan rujukan',intro:'Gunakan pautan rujukan di laman ini supaya pemilikan akaun dan kelayakan rebat boleh disemak.',steps:['Pilih “Buka akaun” di laman web.','Lengkapkan pendaftaran dan pengesahan identiti pada halaman TMGM berkaitan.','Selepas diluluskan, simpan e-mel berdaftar dan nombor akaun dagangan.','Kembali ke laman ini dan hantar permohonan rebat.'],note:'Jangan berikan kata laluan dagangan, kod pengesahan, butiran kad atau imej dokumen identiti.'},
th:{title:'เปิดบัญชีผ่านลิงก์แนะนำ',intro:'ใช้ลิงก์แนะนำบนเว็บไซต์เพื่อให้สามารถตรวจสอบการเชื่อมโยงบัญชีและสิทธิ์รับเงินคืนได้',steps:['เลือก “เปิดบัญชี” บนเว็บไซต์','ลงทะเบียนและยืนยันตัวตนบนหน้าของ TMGM ที่เกี่ยวข้อง','หลังอนุมัติ ให้บันทึกอีเมลที่ลงทะเบียนและหมายเลขบัญชีเทรด','กลับมาที่เว็บไซต์และส่งแบบฟอร์มเงินคืน'],note:'ห้ามส่งรหัสผ่านเทรด รหัสยืนยัน ข้อมูลบัตร หรือภาพเอกสารยืนยันตัวตน'}},
rebate:{
'zh-CN':{title:'如何提交满返申请',intro:'完成开户后，在网站表单中提交用于人工核对的基本资料。',steps:['准备姓名、国家或地区、联系方式和TMGM注册邮箱。','填写交易账号并选择账户状态。','确认资料准确，勾选联系和隐私授权。','提交表单并保存系统生成的申请编号。'],note:'申请需要人工审核，提交成功不代表一定获批。'},
'zh-TW':{title:'如何提交滿返申請',intro:'完成開戶後，在網站表單提交用於人工核對的基本資料。',steps:['準備姓名、國家或地區、聯絡方式和TMGM註冊電郵。','填寫交易帳號並選擇帳戶狀態。','確認資料正確，勾選聯絡及私隱授權。','提交表單並保存系統產生的申請編號。'],note:'申請需要人工審核，提交成功不代表一定獲批。'},
en:{title:'Submit a rebate application',intro:'After opening the account, provide the basic details required for manual review.',steps:['Prepare your name, country or region, contact details and TMGM registered email.','Enter the trading account number and choose the account status.','Check the information and accept the contact and privacy consent.','Submit the form and keep the generated reference number.'],note:'Applications require manual review. Submission does not guarantee approval.'},
ms:{title:'Hantar permohonan rebat',intro:'Selepas membuka akaun, berikan maklumat asas yang diperlukan untuk semakan manual.',steps:['Sediakan nama, negara atau wilayah, maklumat hubungan dan e-mel berdaftar TMGM.','Masukkan nombor akaun dagangan dan pilih status akaun.','Semak maklumat dan terima kebenaran hubungan serta privasi.','Hantar borang dan simpan nombor rujukan.'],note:'Permohonan memerlukan semakan manual. Penghantaran tidak menjamin kelulusan.'},
th:{title:'ส่งใบสมัครเงินคืน',intro:'หลังเปิดบัญชี ให้ส่งข้อมูลพื้นฐานที่จำเป็นสำหรับการตรวจสอบโดยเจ้าหน้าที่',steps:['เตรียมชื่อ ประเทศหรือภูมิภาค ช่องทางติดต่อ และอีเมลที่ลงทะเบียนกับ TMGM','กรอกหมายเลขบัญชีเทรดและเลือกสถานะบัญชี','ตรวจสอบข้อมูลและยอมรับการติดต่อและนโยบายความเป็นส่วนตัว','ส่งแบบฟอร์มและเก็บหมายเลขอ้างอิง'],note:'ทุกใบสมัครต้องตรวจสอบโดยเจ้าหน้าที่ การส่งแบบฟอร์มไม่ได้รับประกันการอนุมัติ'}},
existing:{
'zh-CN':{title:'老账户如何查询资格',intro:'注册超过三天的账户不能按新账户流程直接处理，需要先进行人工查询。',steps:['在满返申请表中选择“注册超过三天的老账户”。','填写注册邮箱、交易账号和可联系的社交方式。','在补充说明中填写大致开户注册时间。','提交后等待人工查询账户是否可以办理。'],note:'老账户能否调整归属或开启满返，以最终人工审核结果为准。'},
'zh-TW':{title:'舊帳戶如何查詢資格',intro:'註冊超過三天的帳戶不能按新帳戶流程直接處理，需要先人工查詢。',steps:['在滿返申請表選擇「註冊超過三天的舊帳戶」。','填寫註冊電郵、交易帳號和可聯絡的社交方式。','在補充說明填寫大約開戶時間。','提交後等待人工查詢帳戶是否可以辦理。'],note:'舊帳戶能否調整歸屬或開啟滿返，以最終人工審核結果為準。'},
en:{title:'Request review for an existing account',intro:'Accounts registered more than three days ago require a manual eligibility review.',steps:['Choose “Account older than three days” in the rebate form.','Enter the registered email, trading account number and a contact method.','Add the approximate registration date in the notes.','Submit and wait for a manual account review.'],note:'Any attribution change or rebate eligibility is subject to final manual approval.'},
ms:{title:'Minta semakan untuk akaun sedia ada',intro:'Akaun yang didaftarkan lebih daripada tiga hari memerlukan semakan kelayakan manual.',steps:['Pilih “Akaun lebih tiga hari” dalam borang rebat.','Masukkan e-mel berdaftar, nombor akaun dagangan dan kaedah hubungan.','Nyatakan anggaran tarikh pendaftaran dalam nota.','Hantar dan tunggu semakan manual.'],note:'Sebarang perubahan pemilikan atau kelayakan rebat tertakluk kepada kelulusan akhir.'},
th:{title:'ขอตรวจสอบบัญชีเดิม',intro:'บัญชีที่ลงทะเบียนเกินสามวันต้องผ่านการตรวจสอบสิทธิ์โดยเจ้าหน้าที่',steps:['เลือก “บัญชีเกินสามวัน” ในแบบฟอร์มเงินคืน','กรอกอีเมลที่ลงทะเบียน หมายเลขบัญชีเทรด และช่องทางติดต่อ','ระบุวันที่เปิดบัญชีโดยประมาณในช่องข้อมูลเพิ่มเติม','ส่งแบบฟอร์มและรอการตรวจสอบ'],note:'การเปลี่ยนการเชื่อมโยงบัญชีหรือสิทธิ์รับเงินคืนขึ้นอยู่กับผลการตรวจสอบขั้นสุดท้าย'}},
ib:{
'zh-CN':{title:'如何申请成为 Introducing Broker',intro:'有行业经验或客户渠道的新用户，可以提交 Introducing Broker 申请。',steps:['填写姓名或团队名称、所在地区和联系方式。','说明行业经验、客户来源和主要推广渠道。','提交申请并保存IB申请编号。','审核通过后，登录TMGM客户后台，在“协议及文档”中确认相应协议。'],note:'Introducing Broker申请需要人工沟通和审核，不保证获批。'},
'zh-TW':{title:'如何申請成為 Introducing Broker',intro:'有行業經驗或客戶渠道的新用戶，可以提交 Introducing Broker 申請。',steps:['填寫姓名或團隊名稱、所在地區和聯絡方式。','說明行業經驗、客戶來源和主要推廣渠道。','提交申請並保存IB申請編號。','審核通過後，登入TMGM客戶後台，在「協議及文件」確認相應協議。'],note:'Introducing Broker申請需要人工溝通和審核，不保證獲批。'},
en:{title:'Apply to become an Introducing Broker',intro:'New users with industry experience or client-acquisition channels may submit an Introducing Broker application.',steps:['Provide your name or team name, region and contact method.','Describe your industry experience, client sources and promotion channels.','Submit the application and keep the IB reference number.','After approval, log in to the TMGM client portal and confirm the relevant agreement under Agreements and Documents.'],note:'Introducing Broker applications require communication and manual review. Approval is not guaranteed.'},
ms:{title:'Mohon menjadi Introducing Broker',intro:'Pengguna baharu yang mempunyai pengalaman industri atau saluran pelanggan boleh menghantar permohonan Introducing Broker.',steps:['Berikan nama atau nama pasukan, wilayah dan kaedah hubungan.','Terangkan pengalaman industri, sumber pelanggan dan saluran promosi.','Hantar permohonan dan simpan nombor rujukan IB.','Selepas diluluskan, log masuk portal pelanggan TMGM dan sahkan perjanjian berkaitan di Agreements and Documents.'],note:'Permohonan Introducing Broker memerlukan komunikasi dan semakan manual. Kelulusan tidak dijamin.'},
th:{title:'สมัครเป็น Introducing Broker',intro:'ผู้ใช้ใหม่ที่มีประสบการณ์ในอุตสาหกรรมหรือมีช่องทางลูกค้าสามารถส่งใบสมัคร Introducing Broker ได้',steps:['กรอกชื่อหรือชื่อทีม ภูมิภาค และช่องทางติดต่อ','อธิบายประสบการณ์ แหล่งลูกค้า และช่องทางโปรโมต','ส่งใบสมัครและเก็บหมายเลขอ้างอิง IB','หลังอนุมัติ ให้เข้าสู่พอร์ทัลลูกค้า TMGM และยืนยันข้อตกลงใน Agreements and Documents'],note:'ใบสมัคร Introducing Broker ต้องผ่านการพูดคุยและตรวจสอบโดยเจ้าหน้าที่ ไม่รับประกันการอนุมัติ'}}
};
const common={
'zh-CN':{brand:'TMGM满返网',back:'返回网站',step:'步骤'},'zh-TW':{brand:'TMGM滿返網',back:'返回網站',step:'步驟'},en:{brand:'TMGM Rebate',back:'Back to website',step:'Step'},ms:{brand:'Rebat TMGM',back:'Kembali ke laman',step:'Langkah'},th:{brand:'TMGM เงินคืน',back:'กลับเว็บไซต์',step:'ขั้นตอน'}};
function pageType(){return document.body.dataset.page}
function setLang(lang){if(!common[lang])lang='en';localStorage.setItem('tmgm-lang',lang);document.documentElement.lang=lang;document.getElementById('lang').value=lang;const d=T[pageType()][lang]||T[pageType()].en,c=common[lang];document.getElementById('brand').textContent=c.brand;document.getElementById('back').textContent=c.back;document.getElementById('title').textContent=d.title;document.getElementById('intro').textContent=d.intro;document.getElementById('steps').innerHTML=d.steps.map((s,i)=>`<article class="step"><b>${i+1}</b><h2>${c.step} ${i+1}</h2><p>${s}</p></article>`).join('');document.getElementById('notice').textContent=d.note}
document.getElementById('lang').addEventListener('change',e=>setLang(e.target.value));const saved=localStorage.getItem('tmgm-lang');const b=(navigator.language||'en').toLowerCase();setLang(saved||(b.startsWith('zh-tw')||b.startsWith('zh-hk')?'zh-TW':b.startsWith('zh')?'zh-CN':b.startsWith('ms')?'ms':b.startsWith('th')?'th':'en'));